apiVersion: v1
kind: Service
metadata:
  name: cartitemrouteehost
  labels:
    app: cartitemrouteehost
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 8558
      name: management
    - port: 5055
      name: akka-remote
  selector:
    app: cartitemrouteehost
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cartitemrouteehost
  labels:
    app: cartitemrouteehost
    cluster: cart
spec:
  serviceName: cartitemrouteehost
  replicas: 1
  selector:
    matchLabels:
      app: cartitemrouteehost
  template:
    metadata:
      labels:
        app: cartitemrouteehost
        cluster: cart
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: cartitemrouteehost
        image: vigneshwar11/cartitempoolrouteehost:0.0.9
        resources:
            requests:
                memory: "300M"
                cpu: "50m"
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER__IP
          value: "$(POD_NAME).cartitemrouteehost"
        - name: CLUSTER__PORT
          value: "5055"
        - name: CLUSTER__STARTUPMETHOD
          value: "KubernetesDiscovery"
        - name: CLUSTER__DISCOVERY__SERVICENAME
          value: "cart"
        - name: CLUSTER__READINESSPORT
          value: "11001"
        - name: CLUSTER__PBMPORT
          value: "9110"
        - name: CLUSTER__ISDOCKER
          value: "true"
        livenessProbe:
          tcpSocket:
            port: 11001
        ports:
          - containerPort: 8558
            protocol: TCP
            name: management
          - containerPort: 5055
            protocol: TCP
            name: akka-remote
