apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cartitem-pool
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: cartitemrouteehost
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource